### ISSUE TITLE
Not working in Rails 4.0.0.rc1

### ISSUE THREAD

**Issue by AntonTrapp** [iain/http_accept_language#29]
``` ruby
class ApplicationController < ActionController::Base
  before_filter :set_locale
private
  def set_locale
  I18n.locale = http_accept_language.preferred_language_from(%w{en de})
```

leads to: NameError (undefined local variable or method `http_accept_language' for

tried 1.0.2 and 2.0.0.pre
